/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as MarketRouteImport } from './routes/market'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as ShopShopIdRouteImport } from './routes/shop.$shopId'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as VendorDashboardRouteImport } from './routes/vendor/dashboard'
import { Route as VendorAddProductRouteImport } from './routes/vendor/add-product'
import { Route as VendorRevenueRouteImport } from './routes/vendor/revenue'
import { Route as VendorVideosRouteImport } from './routes/vendor/videos'
import { Route as VendorMessagesRouteImport } from './routes/vendor/messages'
import { Route as TransportDashboardRouteImport } from './routes/transport/dashboard'
import { Route as CustomerDashboardRouteImport } from './routes/customer/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopShopIdRoute = ShopShopIdRouteImport.update({
  id: '/shop/$shopId',
  path: '/shop/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorAddProductRoute = VendorAddProductRouteImport.update({
  id: '/vendor/add-product',
  path: '/vendor/add-product',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRevenueRoute = VendorRevenueRouteImport.update({
  id: '/vendor/revenue',
  path: '/vendor/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorVideosRoute = VendorVideosRouteImport.update({
  id: '/vendor/videos',
  path: '/vendor/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorMessagesRoute = VendorMessagesRouteImport.update({
  id: '/vendor/messages',
  path: '/vendor/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportDashboardRoute = TransportDashboardRouteImport.update({
  id: '/transport/dashboard',
  path: '/transport/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/market': typeof MarketRoute
  '/videos': typeof VideosRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/add-product': typeof VendorAddProductRoute
  '/vendor/revenue': typeof VendorRevenueRoute
  '/vendor/videos': typeof VendorVideosRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/transport/dashboard': typeof TransportDashboardRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/market': typeof MarketRoute
  '/videos': typeof VideosRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/add-product': typeof VendorAddProductRoute
  '/vendor/revenue': typeof VendorRevenueRoute
  '/vendor/videos': typeof VendorVideosRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/transport/dashboard': typeof TransportDashboardRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/market': typeof MarketRoute
  '/videos': typeof VideosRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/add-product': typeof VendorAddProductRoute
  '/vendor/revenue': typeof VendorRevenueRoute
  '/vendor/videos': typeof VendorVideosRoute
  '/vendor/messages': typeof VendorMessagesRoute
  '/transport/dashboard': typeof TransportDashboardRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/market'
    | '/videos'
    | '/product/$productId'
    | '/shop/$shopId'
    | '/auth/signin'
    | '/auth/signup'
    | '/vendor/dashboard'
    | '/vendor/add-product'
    | '/vendor/revenue'
    | '/vendor/videos'
    | '/vendor/messages'
    | '/transport/dashboard'
    | '/customer/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/market'
    | '/videos'
    | '/product/$productId'
    | '/shop/$shopId'
    | '/auth/signin'
    | '/auth/signup'
    | '/vendor/dashboard'
    | '/vendor/add-product'
    | '/vendor/revenue'
    | '/vendor/videos'
    | '/vendor/messages'
    | '/transport/dashboard'
    | '/customer/dashboard'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/market'
    | '/videos'
    | '/product/$productId'
    | '/shop/$shopId'
    | '/auth/signin'
    | '/auth/signup'
    | '/vendor/dashboard'
    | '/vendor/add-product'
    | '/vendor/revenue'
    | '/vendor/videos'
    | '/vendor/messages'
    | '/transport/dashboard'
    | '/customer/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  MarketRoute: typeof MarketRoute
  VideosRoute: typeof VideosRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ShopShopIdRoute: typeof ShopShopIdRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorAddProductRoute: typeof VendorAddProductRoute
  VendorRevenueRoute: typeof VendorRevenueRoute
  VendorVideosRoute: typeof VendorVideosRoute
  VendorMessagesRoute: typeof VendorMessagesRoute
  TransportDashboardRoute: typeof TransportDashboardRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$shopId': {
      id: '/shop/$shopId'
      path: '/shop/$shopId'
      fullPath: '/shop/$shopId'
      preLoaderRoute: typeof ShopShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/add-product': {
      id: '/vendor/add-product'
      path: '/vendor/add-product'
      fullPath: '/vendor/add-product'
      preLoaderRoute: typeof VendorAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/revenue': {
      id: '/vendor/revenue'
      path: '/vendor/revenue'
      fullPath: '/vendor/revenue'
      preLoaderRoute: typeof VendorRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/videos': {
      id: '/vendor/videos'
      path: '/vendor/videos'
      fullPath: '/vendor/videos'
      preLoaderRoute: typeof VendorVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/messages': {
      id: '/vendor/messages'
      path: '/vendor/messages'
      fullPath: '/vendor/messages'
      preLoaderRoute: typeof VendorMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/dashboard': {
      id: '/transport/dashboard'
      path: '/transport/dashboard'
      fullPath: '/transport/dashboard'
      preLoaderRoute: typeof TransportDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  MarketRoute: MarketRoute,
  VideosRoute: VideosRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ShopShopIdRoute: ShopShopIdRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorAddProductRoute: VendorAddProductRoute,
  VendorRevenueRoute: VendorRevenueRoute,
  VendorVideosRoute: VendorVideosRoute,
  VendorMessagesRoute: VendorMessagesRoute,
  TransportDashboardRoute: TransportDashboardRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
